name: Unity Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: |
            Library
            Library.meta
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**', 'Packages/packages-lock.json') }}
          restore-keys: |
            Library-
            Library-${{ hashFiles('Assets/**', 'Packages/**') }}-

      - name: Cache Packages
        uses: actions/cache@v4
        with:
          path: |
            Packages
            Packages.meta
          key: Packages-${{ hashFiles('Packages/packages-lock.json') }}
          restore-keys: |
            Packages-

      - name: Cache Unity Cache
        uses: actions/cache@v4
        with:
          path: |
            .unity/cache
            .unity/packages
          key: UnityCache-${{ hashFiles('Packages/packages-lock.json') }}
          restore-keys: |
            UnityCache-

      - name: Cache Build
        uses: actions/cache@v4
        with:
          path: Builds
          key: Builds-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Builds-

      - name: Unity Builder
        uses: game-ci/unity-builder@v3
        with:
          targetPlatform: StandaloneWindows64
          buildName: PawnShopClient
          buildPath: Builds/Windows
          buildFile: PawnShopClient.exe

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Build
          path: Builds/Windows
          retention-days: 30
